### ISSUE TITLE
Cannot compile project due to build issue.

### ISSUE THREAD

**Issue by jep9816** [igorskh/iperf-swiftui#4]
On line 97 of IperfRunner.swift, I get this error:
            let intervalResultsP: UnsafeMutablePointer<iperf_interval_results>? = extract_iperf_interval_results(stream)

Using xcode 12.5 an building in iOS 12.1

What can be done to fix this?

**Comment by igorskh** [comment]
Hi @jep9816, 
thanks for reporting that.

This is a problem with the underlying [iperf-swift](https://github.com/igorskh/iperf-swift) library, i fixed it there, it should be:
```swift
 let intervalResultsP: UnsafeMutablePointer<iperf_interval_results>? = extract_iperf_interval_results(OpaquePointer(stream))
```


You can try the [fix-opaquepointer](https://github.com/igorskh/iperf-swift/tree/fix-opaquepointer) branch of the [iperf-swift](https://github.com/igorskh/iperf-swift).

Please let me know if it solves the issue.

**Comment by jep9816** [comment]
Hello,
Thanks fo the quick turnaround.I applied your fix and it worked.
Was not sure how to fix, good to see that it was just a simple cast.
regards,
Jerry
    On Wednesday, June 16, 2021, 03:24:22 PM EDT, Igor Kim ***@***.***> wrote:  
 
 


Hi @jep9816,
thanks for reporting that.

This is a problem with the underlying iperf-swift library, i fixed it there, it should be:
 let intervalResultsP: UnsafeMutablePointer<iperf_interval_results>? = extract_iperf_interval_results(OpaquePointer(stream))
You can try the fix-opaquepointer branch of the iperf-swift.

Please let me know if it solves the issue.

**Comment by jep9816** [comment]
Hello,
Will you be able to merge the fix into your master branch.
Jerry
    On Wednesday, June 16, 2021, 03:42:56 PM EDT, Jerry Porter ***@***.***> wrote:  
 
  
Hello,
Thanks fo the quick turnaround.I applied your fix and it worked.
Was not sure how to fix, good to see that it was just a simple cast.
regards,
Jerry
    On Wednesday, June 16, 2021, 03:24:22 PM EDT, Igor Kim ***@***.***> wrote:  
 
 


Hi @jep9816,
thanks for reporting that.

This is a problem with the underlying iperf-swift library, i fixed it there, it should be:
 let intervalResultsP: UnsafeMutablePointer<iperf_interval_results>? = extract_iperf_interval_results(OpaquePointer(stream))
You can try the fix-opaquepointer branch of the iperf-swift.

Please let me know if it solves the issue.

**Comment by igorskh** [comment]
Hello,

I've merged to the library's main branch and also this application should now use GitHub https link by default instead of the local folder.

**Comment by jep9816** [comment]
Hello,
Again thanks for the quick response, I will check it out.
Jerry    On Monday, June 21, 2021, 12:04:49 PM EDT, Igor Kim ***@***.***> wrote:  
 
 


Hello,

I've merged to the library's main branch and also this application should now use GitHub https link by default instead of the local folder.

**Comment by jep9816** [comment]
Hello,
I just tested your main branch and it works!
Also I have a question.
I am creating an iperf config like below, (implemented from your example) and I am setting timeout and duration values.
I am not seeing that the timeout is being triggered.
I "start" the test runner as a server, it goes into "running" state, and I let it sit there for awhile and expect that a timeout will occur if it does not receive a client connection.I was expecting either a stopping or finished state.
Please advise.
        var iperfConfiguration = IperfConfiguration()                iperfConfiguration.address = getInternetAddress()        iperfConfiguration.duration = 1 // in seconds        iperfConfiguration.port = 5004        iperfConfiguration.prot = .udp        iperfConfiguration.role = .server        iperfConfiguration.timeout = 1 // in seconds                iperfRunner = IperfRunner(with: iperfConfiguration)                iperfRunner.start(            onResultReceived,            onErrorReceived,            onNewState        )

Jerry    On Monday, June 21, 2021, 12:31:40 PM EDT, Jerry Porter ***@***.***> wrote:  
 
  
Hello,
Again thanks for the quick response, I will check it out.
Jerry    On Monday, June 21, 2021, 12:04:49 PM EDT, Igor Kim ***@***.***> wrote:  
 
 


Hello,

I've merged to the library's main branch and also this application should now use GitHub https link by default instead of the local folder.

**Comment by igorskh** [comment]
@jep9816 Sorry for the late response. To my understanding, timeout isn't supposed to be used in server mode. 

That what happens when i try to run iperf3 with timeout option:
```bash
iperf3 --connect-timeout=1 -s
``` 

The output is:
```bash
iperf3: parameter error - some option you are trying to set is client only
```

**Comment by jep9816** [comment]
No problem with the late replyI eventually figured out time out is not supported
BTW,  we really like your implementation of opera, have integrated it in one of our apps thanks  Jerry

Sent from Yahoo Mail on Android 
 
  On Sun, Aug 8, 2021 at 5:18, Igor ***@***.***> wrote:   


@jep9816 Sorry for the late response. To my understanding, timeout isn't supposed to be used in server mode.

That what happens when i try to run iperf3 with timeout option:
iperf3 --connect-timeout=1 -s
The output is:
iperf3: parameter error - some option you are trying to set is client only
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
